//
//  Constants.swift
//  Genshin-wiki
//
//  Created by Rixin Li on 5/17/22.
//

import Foundation

struct Constants{
    static var database = "https://api.genshin.dev/"
    
    static var Characters:[String] = ["albedo","aloy","amber","arataki-itto","ayaka","barbara","beidou","bennett","chongyun","diluc","diona","eula","fischl","ganyu","gorou","hu-tao","jean","kaeya","kazuha","keqing","klee","kokomi","lisa","mona","ningguang","noelle","qiqi","raiden","razor","rosaria","sara","sayu","shenhe","sucrose","tartaglia","thoma","traveler-anemo","traveler-electro","traveler-geo","venti","xiangling","xiao","xingqiu","xinyan","yae-miko","yanfei","yoimiya","yun-jin","zhongli"]
    
    static var articfacts:[String] = ["adventurer","archaic-petra","berserker","blizzard-strayer","bloodstained-chivalry","brave-heart","crimson-witch-of-flames","defender-s-will","emblem-of-severed-fate","gambler","glacier-and-snowfield","gladiator-s-finale","heart-of-depth","husk-of-opulent-dreams","instructor","lavawalker","lucky-dog","maiden-beloved","martial-artist","noblesse-oblige","ocean-hued-clam","pale-flame","prayers-for-destiny","prayers-for-illumination","prayers-for-wisdom","prayers-to-springtime","prayers-to-the-firmament","resolution-of-sojourner","retracing-bolide","scholar","shimenawa-s-reminiscence","tenacity-of-the-millelith","the-exile","thundering-fury","thundersoother","tiny-miracle","traveling-doctor","viridescent-venerer","wanderer-s-troupe"]
    
    static var weapons:[String] = ["alley-hunter","amber-catalyst","amenoma-kageuchi","amos-bow","apprentice-s-notes","aquila-favonia","beginner-s-protector","black-tassel","blackcliff-amulet","blackcliff-longsword","blackcliff-pole","blackcliff-slasher","blackcliff-warbow","bloodtainted-greatsword","compound-bow","cool-steel","crescent-pike","dark-iron-sword","deathmatch","debate-club","dodoco-tales","dragon-s-bane","dragonspine-spear","dull-blade","ebony-bow","elegy-for-the-end","emerald-orb","engulfing-lightning","everlasting-moonglow","eye-of-perception","favonius-codex","favonius-greatsword","favonius-lance","favonius-sword","favonius-warbow","ferrous-shadow","festering-desire","fillet-blade","freedom-sworn","frostbearer","hakushin-ring","halberd","hamayumi","harbinger-of-dawn","hunter-s-bow","iron-point","iron-sting","katsuragikiri-nagamasa","kitain-cross-spear","lion-s-roar","lithic-blade","lithic-spear","lost-prayer-to-the-sacred-winds","luxurious-sea-lord","magic-guide","mappa-mare","memory-of-dust","messenger","mistsplitter-reforged","mitternachts-waltz","old-merc-s-pal","otherworldly-story","pocket-grimoire","predator","primordial-jade-cutter","primordial-jade-winged-spear","prototype-archaic","prototype-crescent","prototype-grudge","prototype-malice","prototype-rancour","quartz","rainslasher","raven-bow","recurve-bow","royal-bow","royal-greatsword","royal-grimoire","royal-longsword","royal-spear","rust","sacrificial-bow","sacrificial-fragments","sacrificial-greatsword","sacrificial-sword","seasoned-hunter-s-bow","serpent-spine","sharpshooter-s-oath","silver-sword","skyrider-greatsword","skyrider-sword","skyward-atlas","skyward-blade","skyward-harp","skyward-pride","skyward-spine","slingshot","snow-tombed-starsilver","solar-pearl","song-of-broken-pines","staff-of-homa","summit-shaper","sword-of-descension","the-alley-flash","the-bell","the-black-sword","the-catch","the-flute","the-stringless","the-unforged","the-viridescent-hunt","the-widsith","thrilling-tales-of-dragon-slayers","thundering-pulse","traveler-s-handy-sword","twin-nephrite","vortex-vanquisher","waster-greatsword","white-iron-greatsword","white-tassel","whiteblind","windblume-ode","wine-and-song","wolf-s-gravestone"]
}
